### ISSUE TITLE
requirements problem

### ISSUE THREAD

**Issue by t8ja** [Nuked88/ComfyUI-N-Nodes#10]
git and zipfile 
pip doesn't find anything and halts installation
when done manually, but looking closer at the console when UI loads, it says they're installed... not sure what's going on, but I'm n00b level 

opencv-python overwrites an existing install by 
`WAS Node Suite: OpenCV Python FFMPEG support is enabled`

**Comment by Nuked88** [comment]
what's your enviroment?
There is some problem with open-python and was? because i don't want to use an older version if is not strictly necessary.

**Comment by t8ja** [comment]
yes, it seems Was uses an older version.  The other two aren't causing problems, I was just curious why pip doesn't recognize them since everything in "requirements.txt"  usually returns something

**Comment by Nuked88** [comment]
but there is some error in was? or even the newer version is working? 
The only reason for the error in pip i think is that is running under anothe installation of python that doesn't have those modules installed. Do you have a specific error?

**Comment by t8ja** [comment]
I'm not sure if WAS breaks if the newest version is installed... I was doing so many permutations, I forgot

**Comment by t8ja** [comment]
but I'm sure other nodes keep upgrading numpy and that breaks compatibility with a module called "numba" which then breaks WAS

**Comment by ffdown** [comment]
very BUGest install

**Comment by Nuked88** [comment]
> but I'm sure other nodes keep upgrading numpy and that breaks compatibility with a module called "numba" which then breaks WAS

yes, I've edited my .bat so that after the numpy upgrade due to the installation of llama-cpp-python, it restores it to a version compatible with numba
