### ISSUE TITLE
Error occurred when executing SaveVideo

### ISSUE THREAD

**Issue by TheShadowNYC** [Nuked88/ComfyUI-N-Nodes#11]
Hello, fantastic addition to the workflow btw, thank you for your time and efforts.

I'm currently running into an error when Queuing up multiple runs.

_"Error occurred when executing SaveVideo - list index out of range"_

It works just find when running once. I include two SaveVideo nodes along my workflow. Any ideas what could be causing this?

Thanks

**Comment by Nuked88** [comment]
uhm, it is as if he is trying to save more images than he really has, so for some reason the metadata passed to SaveVideo are wrong. You can try to set manually the metadata with the node "SetMetadataForSaveVideo".

**Comment by TheShadowNYC** [comment]
Thank you for response! Yes, when I removed one of the SaveVideo nodes it doesn't throw error. All good! 

Was curious if there is a way to use a second LoadVideo node to load in an alpha mask video alongside the main source?

**Comment by Nuked88** [comment]
At the moment no because I need to make some changes at the code but i think i have an idea on how to implement it!

**Comment by TheShadowNYC** [comment]
This would be huge deal! Happy to test anything.

**Comment by TheShadowNYC** [comment]
Hello, ok after some further testing on the error mentioned above. It seems to stem from when I reduce the FrameRate in the LoadVideo causing less images to be generated than I'm setting in the Image_Limit setting. 

For example, if my video is 90 Frames Duration and I set the FrameRate=Quarter / Image_Limit=24... it will only be sending (22) images out... so I have to ensure the Image_Limit is equal to whatever that frame count is. Hope that makes sense.

**Comment by Nuked88** [comment]
So, i've made some changes.
It should now be possible to use multiple LoadVideos in the same workflow and I have set an automatic limit for both images_limit and batch_size

**Comment by TheShadowNYC** [comment]
Wonderful! Can't wait to try out!

**Comment by TheShadowNYC** [comment]
works great now!
