### ISSUE TITLE
Suggestion: On/Off switch for AutoPlayLoop on both Load/Save nodes

### ISSUE THREAD

**Issue by TheShadowNYC** [Nuked88/ComfyUI-N-Nodes#13]
In using the nodes throughout today I found myself pausing the videos both in the load and save from auto looping playback. Not sure if anyone else noticing - but seems to slow down machine (I have (1) Load and (2) Save nodes active in my workflow).

**Comment by Nuked88** [comment]
Yes, I already had an idea to implement it! Currently I don't have much time to do it but I'll add it as soon as I can!

**Comment by Nuked88** [comment]
I've implemented it in the Load node!, In the Save node doesn't seems to work no matter what so for now is not possible there :(

**Comment by TheShadowNYC** [comment]
Much appreciated! Thank you for all the time/effort on these.
