### ISSUE TITLE
Quirk: Second LoadVideo Node reverts back to default size on grid upon loading

### ISSUE THREAD

**Issue by TheShadowNYC** [Nuked88/ComfyUI-N-Nodes#14]
Noticed that my second LoadVideo node, in a Group panel if that matters, will revert size on the grid layout back to the default and not save like the first LoadVideo node. Little QOL thing, but I can see manifesting when sharing workflows.

**Comment by Nuked88** [comment]
I hope I didn't screw up anything but it should be fixed now!
