### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_cpp'

### ISSUE THREAD

**Issue by Romanio1997** [Nuked88/ComfyUI-N-Nodes#16]
When running in the console cmd shows this error:

### ComfyUI Revision: 1612 [2ec6158e] | Released on '2023-10-22'
moviepy is already installed.
cv2 is already installed.
git is already installed.
zipfile is already installed.
skbuild is already installed.
Loaded 3.x/4.x HD model.
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\__init__.py", line 90, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py", line 3, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

**Comment by Nuked88** [comment]
Did you run one of the .bat files as described in the readme?
If not, it's normal that you have that error.

**Comment by Romanio1997** [comment]
I figured out three hours spent on the solution I have a portable build and need to install for python environment in ComfyUI_windows_portable, but it installs for general python so it does not work this happens also because the module ComfyUI-N-Nodes is not installed through the ComfyUI manager so I have eliminated all errors of this kind in any other similar modules. 

**To fix the error "ModuleNotFoundError: No module named 'llama_cpp'" in ComfyUI_windows_portable, follow these steps:**

Open a command prompt or PowerShell in the c:\AI\ComfyUI_windows_portable\ComfyUI\ folder.
Create a virtual environment by running the following command:
python.exe -m venv venv
Activate the virtual environment by running the following command:
venv\Scripts\activate
Install the llama-cpp-python library by running the following command:
pip install llama-cpp-python
Copy the llama-cpp-python library and its dependencies from the c:\AI\ComfyUI_windows_portable\ComfyUI\venv\Lib\site-packages\ folder to the c:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ folder.

Detailed instructions:
I'm the one with the directories, but each c:\AI will have its own:
Open a command prompt or PowerShell in the c:\AI\ComfyUI_windows_portable\ComfyUI\ folder.

To create a virtual environment, run the following command:
python.exe -m venv venv
This will create a virtual environment named venv in the current directory.

To activate the virtual environment, run the following command:
venv\Scripts\activate
This will set the current directory to the venv virtual environment.

To install the llama-cpp-python library, run the following command:
pip install llama-cpp-python
This will install the llama-cpp-python library and all its dependencies in the virtual environment.

To copy the llama-cpp-python library and its dependencies to the python_embeded directory, run the following commands:
cd c:\AI\ComfyUI_windows_portable\ComfyUI\venv\Lib\site-packages\
xcopy . c:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\
This will copy all of the files and folders in the llama-cpp-python directory to the python_embeded directory.

Once you have completed these steps, you should be able to run ComfyUI_windows_portable without any errors.

**Comment by Nuked88** [comment]
uhm, i don't understand one thing: do you want to use the gptnode?
If you don't want to use it you can just ignore the "llama_cpp error" because the only downside of that error is that only the GPTnodes will not be loaded, otherwise is better to use llama compiled with cuda (if you have a nvidia GPU) because it will be way faster to run.
In the case you want to use it CPU only (and at this point i will made a batch even for that) you can run:

`python.exe -s -m pip install llama-cpp-python `

from the python_embeded directory of the ComfyUI portable build (which is the one I am also using!)

**Comment by Nuked88** [comment]
Done! ae64a47e83efff2c33564cb2c372b03ec4b3c8ff

**Comment by angrysky56** [comment]
Same error, fails to import your nodes, tried the update.bat, tried the pip install llama. Trying to run with LM Studio or ooba.

F:\comfyNodeGPT>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2023-12-12 04:03:39.232025
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: F:\comfyNodeGPT\python_embeded\python.exe
** Log path: F:\comfyNodeGPT\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\comfyNodeGPT\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 64821 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V1.11.5)
### ComfyUI Revision: 1810 [b0aab1e4] | Released on '2023-12-11'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.jsonF:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT\AutoUpdate.json

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Traceback (most recent call last):
  File "F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT\API_Nodes\llama-cpp.py", line 9, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\comfyNodeGPT\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT\__init__.py", line 127, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT\API_Nodes\llama-cpp.py", line 21, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

Cannot import F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT module for custom nodes: No module named 'llama_cpp'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT
   0.3 seconds: F:\comfyNodeGPT\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server
![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/113643118/93b9a03f-7fa7-4a48-b4c6-a499f0512395)

**Comment by Nuked88** [comment]
Sorry but what the hell is NodeGPT? This is not my node.

**Comment by angrysky56** [comment]
lol, I am sorry, I thought it was yours, it is the node based gpt you can find via the comfyUI manger.

**Comment by Nuked88** [comment]
ohh ok! No problem!

**Comment by nishan129** [comment]
I got : Command errored out with exit status 1:
   command: 'C:\Users\Nishant Borkar\anaconda3\python.exe' 'C:\Users\Nishant Borkar\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\NISHAN~1\AppData\Local\Temp\tmp8t5w6odn'
       cwd: C:\Users\Nishant Borkar\AppData\Local\Temp\pip-install-m7n9ozbj\llama-cpp-python_8fa140cccd3747219dcf9476c85bf6f9
  Complete output (20 lines):
  *** scikit-build-core 0.9.4 using CMake 3.29.3 (wheel)
  *** Configuring CMake...
  2024-05-29 17:23:09,190 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
  loading initial cache file C:\Users\NISHAN~1\AppData\Local\Temp\tmpdr1671xv\build\CMakeInit.txt
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:3 (project):
    Running

     'nmake' '-?'

    failed with:

     no such file or directory


  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!

  *** CMake configuration failed
  ----------------------------------------
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python which use PEP 517 and cannot be installed directly
 error
