### ISSUE TITLE
ComfyUI-N-Nodes causes first sampling time to become longer

### ISSUE THREAD

**Issue by xianrenzhang0318** [Nuked88/ComfyUI-N-Nodes#17]
After ComfyUI-N-Nodes is installed, even if this node is not used, as long as the output size is adjusted, it will wait for a long time in the sampler and vae decoding. Deleting ComfyUI-N-Nodes does not cause this situation
![微信截图_20231025201248](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/131863645/44dd7e61-9e4d-45ec-9e98-ac2467021f8f)

**Comment by Nuked88** [comment]
Sorry but, what do you mean "as long as the output size is adjusted"?

**Comment by xianrenzhang0318** [comment]
Sorry, I didn't express myself well. When I started comfyui for the first time, even if I didn't use any function of Comfyui-N-Nodes, the sampler would freeze for about 30 seconds (it was not a problem of switching large models), as long as I changed the sampling Any data in the sampler will also freeze for about 30 seconds. I excluded other nodes one by one. As long as I delete Comfyui-N-Nodes, this situation will not occur. I don’t know if it is a conflict between nodes. , or it is a bug in the node itself. In short, after changing the sampler data (including the number of seeds, image resolution, etc.), the first sampling will cause the sampler and VAE to freeze for a long time. The problem occurred after I installed Comfyui-N-Nodes.

**Comment by xianrenzhang0318** [comment]
> Sorry but, what do you mean "as long as the output size is adjusted"?🔄  ❓

Sorry, I didn't express myself well. When I started comfyui for the first time, even if I didn't use any function of Comfyui-N-Nodes, the sampler would freeze for about 30 seconds (it was not a problem of switching large models), as long as I changed the sampling Any data in the sampler will also freeze for about 30 seconds. I excluded other nodes one by one. As long as I delete Comfyui-N-Nodes, this situation will not occur. I don’t know if it is a conflict between nodes. , or it is a bug in the node itself. In short, after changing the sampler data (including the number of seeds, image resolution, etc.), the first sampling will cause the sampler and VAE to freeze for a long time. The problem occurred after I installed Comfyui-N-Nodes.

**Comment by xianrenzhang0318** [comment]
> Sorry but, what do you mean "as long as the output size is adjusted"?🔄  ❓

Sorry, I didn't express myself well enough. When I first start comfyui, even though I'm not using any features of Comfyui-N-Nodes, the sampler freezes for about 30 seconds (not a problem of switching large models), as soon as I change the image resolution and batch, sample The device will also freeze for approximately 30 seconds. I have excluded all other nodes one by one. As soon as I remove Comfyui-N-Nodes, this doesn't happen. I don’t know if there is a conflict between nodes. , or it may be a bug in the node itself. In short, changing the input data of the sampler will cause the sampler and VAE to freeze for a long time. This is a problem I had after installing Comfyui-N-Nodes.

**Comment by xianrenzhang0318** [comment]
As shown in the picture above, the sampler and VAE decoder will stay motionless for a long time, and the sampling progress bar will appear after about 30 seconds.

**Comment by Nuked88** [comment]
ok now i got it but i still doen't have any idea of why this is happening to you. Con you give me a list of all the nodes you have installed?

**Comment by xianrenzhang0318** [comment]
I have confirmed that there is no conflict between Comfyui-N-Nodes and other nodes. This will happen even if I only keep Comfyui-N-Nodes. As shown in the picture, comparison of two sampling times. One is without Comfyui-N-Nodes installed, and the other is with Comfyui-N-Nodes installed.
This situation will only occur after changing the model and image resolution, and every subsequent sampling will be normal.
![1](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/131863645/1b4ff94d-2c94-4165-b3bf-870361be1aae)
![2](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/131863645/5371e278-b59f-445a-bbdb-3f209f1bf7f8)

**Comment by xianrenzhang0318** [comment]
This is a list of all my nodes：

AIGODLIKE-ComfyUI-Translation
cg-image-picker
comfy-qr
ComfyMath
ComfyUI-Advanced-ControlNet
comfyui-animatediff
ComfyUI-AnimateDiff-Evolved
ComfyUI-Bmad-DirtyUndoRedo
ComfyUI-Custom-Scripts
comfyui-dynamicprompts
ComfyUI-Impact-Pack
ComfyUI-Inspire-Pack
ComfyUI-LCM
ComfyUI-Manager
ComfyUI-post-processing-nodes
comfyui-reactor-node
ComfyUI-Vextra-Nodes
ComfyUI-VideoHelperSuite
ComfyUI-WD14-Tagger
ComfyUI-Workflow-Component
ComfyUI_ADV_CLIP_emb
ComfyUI_Comfyroll_CustomNodes
comfyui_controlnet_aux_stable
ComfyUI_Custom_Nodes_AlekPet
ComfyUI_Cutoff
comfyui_dagthomas
ComfyUI_Dave_CustomNode
ComfyUI_experiments
ComfyUI_FastVAEDecorder_SDXL
ComfyUI_FizzNodes
ComfyUI_IPAdapter_plus
ComfyUI_JPS-Nodes
Comfyui_Lama
ComfyUI_LatentToRGB
ComfyUI_NestedNodeBuilder
ComfyUI_Noise
ComfyUI_restart_sampling
ComfyUI_SeeCoder
comfyui_segment_anything
ComfyUI_smZNodes
ComfyUI_TiledKSampler
ComfyUI_UltimateSDUpscale
ControlNet-LLLite-ComfyUI
Cup-ClipBoard
Derfuu_ComfyUI_ModdedNodes
efficiency-nodes-comfyui
facerestore_cf
images-grid-comfy-plugin
IPAdapter-ComfyUI
masquerade-nodes-comfyui
NAME.TXT
sd-dynamic-thresholding
sdxl-recommended-res-calc
sdxl_prompt_styler
SeargeSDXL
stability-ComfyUI-nodes
was-node-suite-comfyui
__pycache__

**Comment by xianrenzhang0318** [comment]
> ok now i got it, thank you! but i still doesn't have any idea of why this is happening to you. Con you give me a list of all the nodes you have installed?好的，现在我明白了，谢谢！但我仍然不知道为什么这会发生在你身上。你给我一个你已安装的所有节点的列表吗？

This is a list of all my nodes：
这是我所有节点的列表：

AIGODLIKE-ComfyUI-Translation
AIGODLIKE-ComfyUI-翻译

cg-image-picker  cg-图像选择器
comfy-qr  舒适qr
ComfyMath  舒适数学
ComfyUI-Advanced-ControlNet
ComfyUI-高级-ControlNet

comfyui-animatediff
ComfyUI-AnimateDiff-Evolved
ComfyUI-Bmad-DirtyUndoRedo
ComfyUI-Bmad-Dirty撤消重做

ComfyUI-Custom-Scripts  ComfyUI-自定义脚本
comfyui-dynamicprompts 舒适的动态提示
ComfyUI-Impact-Pack ComfyUI 冲击包
ComfyUI-Inspire-Pack
ComfyUI-LCM 舒适UI-LCM
ComfyUI-Manager ComfyUI管理器
ComfyUI-post-processing-nodes
ComfyUI-后处理-节点

comfyui-reactor-node  comfyui 反应器节点
ComfyUI-Vextra-Nodes  ComfyUI-Vextra-节点
ComfyUI-VideoHelperSuite
ComfyUI-WD14-Tagger  ComfyUI-WD14-标记器
ComfyUI-Workflow-Component
ComfyUI-工作流程组件

ComfyUI_ADV_CLIP_emb
ComfyUI_Comfyroll_CustomNodes
comfyui_controlnet_aux_stable
ComfyUI_Custom_Nodes_AlekPet
ComfyUI_Cutoff
comfyui_dagthomas
ComfyUI_Dave_CustomNode
ComfyUI_experiments  ComfyUI_实验
ComfyUI_FastVAEDecorder_SDXL
ComfyUI_FizzNodes
ComfyUI_IPAdapter_plus
ComfyUI_JPS-Nodes  ComfyUI_JPS-节点
Comfyui_Lama
ComfyUI_LatentToRGB
ComfyUI_NestedNodeBuilder
ComfyUI_Noise  ComfyUI_噪音
ComfyUI_restart_sampling
ComfyUI_SeeCoder
comfyui_segment_anything
ComfyUI_smZNodes
ComfyUI_TiledKSampler
ComfyUI_UltimateSDUpscale
ControlNet-LLLite-ComfyUI
Cup-ClipBoard 杯夹板
Derfuu_ComfyUI_ModdedNodes
efficiency-nodes-comfyui
效率节点-comfyui

facerestore_cf  面部恢复_cf
images-grid-comfy-plugin
图像网格舒适插件

IPAdapter-ComfyUI
masquerade-nodes-comfyui
伪装节点 comfyui

NAME.TXT  名称.TXT
sd-dynamic-thresholding  SD-动态阈值
sdxl-recommended-res-calc
sdxl-推荐-res-calc

sdxl_prompt_styler
SeargeSDXL 塞吉SDXL
stability-ComfyUI-nodes 稳定性-ComfyUI-节点
was-node-suite-comfyui
pycach

**Comment by xianrenzhang0318** [comment]
> ok now i got it, thank you! but i still doesn't have any idea of why this is happening to you. Con you give me a list of all the nodes you have installed?

This is a list of all my nodes：

AIGODLIKE-ComfyUI-Translation
cg-image-picker
comfy-qr
ComfyMath
ComfyUI-Advanced-ControlNet
comfyui-animatediff
ComfyUI-AnimateDiff-Evolved
ComfyUI-Bmad-DirtyUndoRedo
ComfyUI-Custom-Scripts
comfyui-dynamicprompts
ComfyUI-Impact-Pack
ComfyUI-Inspire-Pack
ComfyUI-LCM
ComfyUI-Manager
ComfyUI-post-processing-nodes
comfyui-reactor-node
ComfyUI-Vextra-Nodes
ComfyUI-VideoHelperSuite
ComfyUI-WD14-Tagger
ComfyUI-Workflow-Component
ComfyUI_ADV_CLIP_emb
ComfyUI_Comfyroll_CustomNodes
comfyui_controlnet_aux_stable
ComfyUI_Custom_Nodes_AlekPet
ComfyUI_Cutoff
comfyui_dagthomas
ComfyUI_Dave_CustomNode
ComfyUI_experiments
ComfyUI_FastVAEDecorder_SDXL
ComfyUI_FizzNodes
ComfyUI_IPAdapter_plus
ComfyUI_JPS-Nodes
Comfyui_Lama
ComfyUI_LatentToRGB
ComfyUI_NestedNodeBuilder
ComfyUI_Noise
ComfyUI_restart_sampling
ComfyUI_SeeCoder
comfyui_segment_anything
ComfyUI_smZNodes
ComfyUI_TiledKSampler
ComfyUI_UltimateSDUpscale
ControlNet-LLLite-ComfyUI
Cup-ClipBoard
Derfuu_ComfyUI_ModdedNodes
efficiency-nodes-comfyui
facerestore_cf
images-grid-comfy-plugin
IPAdapter-ComfyUI
masquerade-nodes-comfyui
NAME.TXT
sd-dynamic-thresholding
sdxl-recommended-res-calc
sdxl_prompt_styler
SeargeSDXL
stability-ComfyUI-nodes
was-node-suite-comfyui
__pycache__

**Comment by xianrenzhang0318** [comment]
After I delete Comfyui-N-Nodes, the picture appears
![1](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/131863645/4c66a9b0-f7ea-484a-879a-bf0470dd31a0)

**Comment by xianrenzhang0318** [comment]
After I delete Comfyui-N-Nodes, this appears:

J:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_urldispatcher.py:189: DeprecationWarning: Bare functions are deprecated, use async ones
  warnings.warn(
J:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_urldispatcher.py:189: DeprecationWarning: Bare functions are deprecated, use async ones
  warnings.warn(
![1](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/131863645/d0961cbc-e0b4-4a80-923a-3387ffdd8e63)

**Comment by xianrenzhang0318** [comment]
Starting comfyui will scan the temp\n-suite folder
![000](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/131863645/bfcb7dd6-04e6-4d8c-b49f-8e57a77a152b)

**Comment by Nuked88** [comment]
Thanks man! I'm sorry but I haven't had a chance to check the problem until now, and i found the problem! (was an optional settings in the Frame Interpolator Node that for whatever reason was executed even if the node was not loaded.
I've never noticed because my system was increasing only to few seconds (like from 1s to 8s)
Do a git pull and now it should be ok!

**Comment by xianrenzhang0318** [comment]
> Thanks man! I'm sorry but I haven't had a chance to check the problem until now, and i found it! (was an optional settings in the Frame Interpolator Node that for whatever reason was executed even if the node was not loaded.谢啦！抱歉，直到现在我还没有机会检查问题，但我发现了！ （是帧插值器节点中的一个可选设置，无论出于何种原因，即使未加载该节点，也会执行该设置。 I've never noticed because my system was increasing only to few seconds (like from 1s to 8s) 我从来没有注意到，因为我的系统只增加了几秒（比如从 1 秒到 8 秒） Do a git pull and now it should be ok! 执行 git pull 现在应该没问题了！

Thank you, it’s no problem anymore. This is a very good node.
