### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by boricuapab** [Nuked88/ComfyUI-N-Nodes#2]
Got this error when trying to inference.

```
Traceback (most recent call last):
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py", line 50, in load_gpt_checkpoint
    llm = Llama(model_path=ckpt_path,n_gpu_layers=gpu_layers,verbose=False,n_threads=n_threads, n_ctx=4000, )
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\llama_cpp\llama.py", line 319, in __init__
    with suppress_stdout_stderr():
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\llama_cpp\utils.py", line 11, in __enter__
    self.old_stdout_fileno_undup = sys.stdout.fileno()
AttributeError: 'Logger' object has no attribute 'fileno'
```

I was able to build llama cpp from source using cuda toolkit 12.1

**Comment by boricuapab** [comment]
The LLM I tried using was

TheBloke/airoboros-l2-7b-gpt4-1.4.1-GGML

**Comment by boricuapab** [comment]
![comfyLlamaError](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/61924816/694a3117-78b2-422e-9e12-3e6afac079bd)

**Comment by Nuked88** [comment]
Hi,
it's a weird error that is more from llama.cpp that from me but it could be related to this: https://github.com/Nuked88/ComfyUI-N-Nodes/issues/1#issuecomment-1712745028
do a **git pull** in the ComfyUI-N-Nodes folder for update this repo at the latest version and launch install_dependency_ggml_models.bat and see if it works

**Comment by boricuapab** [comment]
I still get the error with gguf models also

**Comment by boricuapab** [comment]
I updated and wanted to mention that the version of numpy that gets installed has a bit of conflict with was nodes

```
Traceback (most recent call last):
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\numba\__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")
ImportError: Numba needs NumPy 1.24 or less

Cannot import C:\sdComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: Numba needs NumPy 1.24 or less
```

**Comment by Nuked88** [comment]
Hi, so it's probably something related to some dependency also for the first error (Thanks for the info btw).
You can quickly verify that if you just unzip the comfyUI installer in another folder and install only this node. I tried to use a model from the airoboros-l2-7b-gpt4-1.4.1-GGML repository and is working fine to me
Also, sadly I cannot "hard code" the downgrade of NumPy to something like 1.24.5 because I'm afraid to broke some compatibility with llama.cpp itself
But if you want to downgrade it just run `python.exe -s -m pip install numpy==1.24.4 --force-reinstall --upgrade` from the **python_embeded** directory

**Comment by boricuapab** [comment]
Works on a fresh install of comfy with only installing these 2 custom nodes

![extra2nodes](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/61924816/a405f32e-440b-4f11-a304-378ebd8e9d82)

![ggmlWorks](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/61924816/d76fb8e4-5f74-4269-b605-58f6559d1a1c)

I'll investigate what's causing it to not work when all these other custom nodes are installed

![otherCustomNodes](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/61924816/82abc0cf-c36c-4bdc-9b64-e81ea90bda56)

Thanks for your work though, I was looking to be able to use local llms along with comfy for so long and you've delivered.

**Comment by theelefant** [comment]
Regarding the error: "AttributeError: 'Logger' object has no attribute 'fileno'", it occurred in my case due to the "ComfyUI-Manager" custom node. When I commented out line 41 in the "prestartup_script.py" file within the "ComfyUI-Manager", the error disappeared.

**Comment by boricuapab** [comment]
> Regarding the error: "AttributeError: 'Logger' object has no attribute 'fileno'", it occurred in my case due to the "ComfyUI-Manager" custom node. When I commented out line 41 in the "prestartup_script.py" file within the "ComfyUI-Manager", the error disappeared.

Thanks for the tip, works now, I've also tested being able to use ggml v3 and gguf models

![ggufWorks2](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/61924816/ff14ba21-bd2f-460e-85d1-a0a09feb2ff2)

**Comment by Nuked88** [comment]
Perfect! I'm glad to hear that!
Thanks even to [theelefant](https://github.com/theelefant) for the tips!

**Comment by txirrindulari** [comment]
> Regarding the error: "AttributeError: 'Logger' object has no attribute 'fileno'", it occurred in my case due to the "ComfyUI-Manager" custom node. When I commented out line 41 in the "prestartup_script.py" file within the "ComfyUI-Manager", the error disappeared.

What is it on line 41?
My prestartup_script.py looks like:
41                else:
42                   self.sync_write(message)

**Comment by txirrindulari** [comment]
> > > Regarding the error: "AttributeError: 'Logger' object has no attribute 'fileno'", it occurred in my case due to the "ComfyUI-Manager" custom node. When I commented out line 41 in the "prestartup_script.py" file within the "ComfyUI-Manager", the error disappeared.
> > 
> > 
> > What is it on line 41? My prestartup_script.py looks like: 41 else: 42 self.sync_write(message)
> 
> The `prestartup_script.py` file has changed in recent updates of ComfyUI-Manager. To make the nodes work properly, you now need to comment out lines 75 and 76:
> 
> ```python
>     #sys.stdout = Logger(True)
>     #sys.stderr = Logger(False)
> ```
> 
> Essentially, what's happening is that ComfyUI-Manager is 'hijacking' the `sys.stdout` object and replacing it with its own `Logger` class, which lacks the `fileno()` method. As far as I understand, there's little that Nuked can do to mitigate this issue, since it's `LLama.cpp` that requires the `fileno()` method.

It works now!!. Thank you to everyone who creates and makes it possible for us to use these tools.

**Comment by theelefant** [comment]
I've asked [ltdrdata](https://github.com/ltdrdata) to update the [ComfyUI-Manager](https://github.com/ltdrdata/ComfyUI-Manager) by adding a `fileno()` method to the `prestartup_script.py`. This way, hopefully, there won't be a need to modify that file in the future. The patch is already commited and should be availble soon.

https://github.com/ltdrdata/ComfyUI-Manager/issues/117#issue-1913361188

**Comment by Nuked88** [comment]
> I've asked [ltdrdata](https://github.com/ltdrdata) to update the [ComfyUI-Manager](https://github.com/ltdrdata/ComfyUI-Manager) by adding a `fileno()` method to the `prestartup_script.py`. This way, hopefully, there won't be a need to modify that file in the future. The patch is already commited and should be availble soon.
> 
> [ltdrdata/ComfyUI-Manager#117 (comment)](https://github.com/ltdrdata/ComfyUI-Manager/issues/117#issue-1913361188)

Thank you ❤️
