### ISSUE TITLE
samples presented in the README.md file?

### ISSUE THREAD

**Issue by vvip2u** [Nuked88/ComfyUI-N-Nodes#20]
If someone want to use this repo, could you pls provide some instructions and images? samples?

**Comment by Nuked88** [comment]
Hi,
for now i have some videos, when i have time i will upload some workflows

Those are mine
https://www.youtube.com/watch?v=nMyiuiWjiEc
https://www.youtube.com/watch?v=asMgkwTDAQQ

And this if from  [boricuapab](https://github.com/boricuapab)
https://www.youtube.com/watch?v=gzTqXbF0S-w

**Comment by Nuked88** [comment]
README improved!
