### ISSUE TITLE
import failed :(

### ISSUE THREAD

**Issue by BansheeStudio** [Nuked88/ComfyUI-N-Nodes#26]
![WindowsTerminal_my9OKjviuE](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/113316414/b33cbf12-9abf-487b-adff-c95c81a6e299)

**Comment by Nuked88** [comment]
Hi. 
Without a full log (all the text in the console from the time ComfyUI was started until the time of the reported bug) i will be not able to help you in any way man.
