### ISSUE TITLE
Load Video Node METADATA

### ISSUE THREAD

**Issue by Aljnk** [Nuked88/ComfyUI-N-Nodes#29]
Hi. I am using your Load Video Node and I want to get all the metadata from it separately. I have tried many things to separate your metadata by nodes but nothing. Do you know a way to do this?

**Comment by Aljnk** [comment]
I found the way, but it does not look so good :)

<img width="1101" alt="Screenshot_1" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/a18025e9-e83b-4095-bf7f-1c5939e3190b">

**Comment by Nuked88** [comment]
I've added:
- META_FPS: Frame rate.
- META_N_FRAMES: Number of frames.
To LoadVideo node
