### ISSUE TITLE
Local Tiny AI Vision Language Model (1.6B)

### ISSUE THREAD

**Issue by BenderBlender** [Nuked88/ComfyUI-N-Nodes#30]
I wanted to use “blip analyze image” in my workflow, but after the next comfyui updates this node unfortunately stopped working. But an excellent neural network model with vision support has appeared (Local Tiny AI Vision Language Model (1.6B)).

![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/116355906/f3f41c73-b828-43fb-8d95-aee9240ab8c8)

**It would be great if you could add support for this model to the nodes!**
https://github.com/vikhyat/moondream?tab=readme-ov-file

![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/116355906/6aa00187-06d7-43ea-9e91-a0eb23fcd360)

https://www.youtube.com/watch?v=oDGQrOlmC1s

**Comment by Nuked88** [comment]
Damn this is interesting! Thanks for share! I didn0t know that there are such a small models able to do that (i was suck to the main LLava model that is great but also really heavy) , i will definitly check it out!

**Comment by BenderBlender** [comment]
I collected a work flow with your node, which draws itself and then tries to improve its creation using this pattern recognition model )))

![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/116355906/b846732d-49c8-4b83-a61d-159aac143c3a)
![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/116355906/14b2ee5e-7d38-4b59-b1dd-eed48998a83f)
![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/116355906/b32ae3cd-c07b-4805-a274-b788b4735630)
![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/116355906/d60d4901-1fe6-4509-b285-3fe914f9211d)

**Comment by Nuked88** [comment]
Very nice!

**Comment by BenderBlender** [comment]
The guys have already added a 2nd model, it seems even better than the first
https://github.com/zhongpei/Comfyui_image2prompt
![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/116355906/9a2b1dc6-3428-4011-a5f4-da988f2b64cd)

**Comment by BenderBlender** [comment]
Please advise a good model (GGUF GPT) that will work with your node. There are so many of them that my eyes are running wild. Maybe there is some kind of rating?

**Comment by BenderBlender** [comment]
![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/116355906/72f14bd9-78ba-4cd7-9f98-a2750efdbd05)
![image](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/116355906/1c17f184-bfd2-4121-912c-59a4e503d4fb)

**Comment by Nuked88** [comment]
> Please advise a good model (GGUF GPT) that will work with your node. There are so many of them that my eyes are running wild. Maybe there is some kind of rating?
As you said there are too many of them so i really cannot say which is better than which but yes there are ALOT of benchmark tests used for rating  an llm models, you can have a summary here https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard
or here:
https://eqbench.com/

**Comment by Nuked88** [comment]
ok i've added support for llava model, moondream and joytag. I'm trying to add interlm (i did most of the code ) but i'm having some issues, plus being a heavier model I have to give it less priority so I think I will add it but not right away
