### ISSUE TITLE
GPTSampler Error

### ISSUE THREAD

**Issue by Aljnk** [Nuked88/ComfyUI-N-Nodes#33]
**Describe the bug**
GPTSampler and GPTLoaderSimple stopped working after update.

**To Reproduce**
Just Start

**Screenshots**
<img width="493" alt="Screenshot_1" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/eaf29dba-66e8-422b-8ac6-58d732119860">
<img width="656" alt="Screenshot_2" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/e009ecae-dc74-4cbb-9875-526024acdca2">

**Desktop (please complete the following information):**
 - OS: Window 11
 - chrome (updated)

**Comment by Nuked88** [comment]
Please read the [readme](https://github.com/Nuked88/ComfyUI-N-Nodes), this is happen because unfortunatly i had to change the name of the node to avoid future possible conflict.

**Comment by Aljnk** [comment]
I see that the names have been changed.
<img width="502" alt="Screenshot_1" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/b4cfdb11-bae1-49d7-99d4-7bc8ab961374">


but I can't find new nodes
<img width="624" alt="Screenshot_2" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/ef4b88e0-b21d-41e8-987f-f2233bc2ddf4">

**Comment by Aljnk** [comment]
<img width="283" alt="Screenshot_3" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/b02a3c50-f84b-48c1-8ee9-719850b74b76">
<img width="271" alt="Screenshot_4" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/175f494a-3145-4b7e-87c1-345b61fd1c65">
<img width="235" alt="Screenshot_5" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/9f4725ee-a980-4bd8-b177-5ff1e8c4a8d5">

**Comment by Nuked88** [comment]
Take a look at the confyui startup logs, maybe there are some errors

**Comment by Aljnk** [comment]
```
Traceback (most recent call last):
  File "...\Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI-N-Nodes\__init__.py", line 60, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "...\Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py", line 12, in <module>
    from moondream_repo.moondream.moondream import Moondream
ModuleNotFoundError: No module named 'moondream_repo.moondream.moondream'
```

**Comment by Nuked88** [comment]
Can i have the full log please? 🤣

**Comment by Aljnk** [comment]
[comfyui.log](https://github.com/Nuked88/ComfyUI-N-Nodes/files/14298861/comfyui.log)

**Comment by Aljnk** [comment]
<img width="384" alt="Screenshot_1" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/446e5741-39d1-4458-ac9a-19df47627877">
<img width="291" alt="Screenshot_2" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/34a1a4d5-6c73-406b-900d-800bb8c12d15">
<img width="444" alt="Screenshot_3" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/746e0e6b-3cc5-42cc-9589-a166bf8a16de">

I'm not sure, but the code:
`from moondream_repo.moondream.moondream import Moondream`
should include the file `moondream.py`?
But I don't see the file `moondream.py` in the folder `...\custom_nodes\ComfyUI-N-Nodes\libs\moondream_repo\moondream\`

**Comment by Aljnk** [comment]
1. I delete the `moondream_repo` folder.
2. Run my `CMD` with the command
git clone https://github.com/Nuked88/moondream.git
3. Rename the first `moondream` folder to `moondream_repo`
4. Run my ComfyUI - everything works :)

5. Then I delete the `moondream_repo` folder again (to install it from your code)
6. Run my ComfyUI and check the `moondream_repo/moondream` folder - it still without moondream.py
but
everything works :)

**Comment by Nuked88** [comment]
Hi! Yes, it worked because in the meantime I was fixing it xD. 
It was a problem with the checkout ID I was using on the Moondream repo I forked. 
Now I've put all the files on the current branch of the Moondream repository. If you delete the ComfyUI-N-Nodes folder and then do a git clone, everything should work as expected!

**Comment by Aljnk** [comment]
Thanks a lot!
