### ISSUE TITLE
Moondream Model Output Error (tuple)

### ISSUE THREAD

**Issue by Aljnk** [Nuked88/ComfyUI-N-Nodes#34]
**Describe the bug**
The model (Moondream) does not return a string.

**To Reproduce**
See screenshot

**Screenshots**
<img width="570" alt="Screenshot_1" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/e2f872b7-d7f2-4dfb-981a-3668419f3699">
<img width="1022" alt="Screenshot_2" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/11256478/588d0add-46f3-4266-a182-971a8f58e635">

**Comment by Nuked88** [comment]
Should be fixed now, thanks!
