### ISSUE TITLE
N-nodes doesnt work 

### ISSUE THREAD

**Issue by timraw** [Nuked88/ComfyUI-N-Nodes#36]
**Describe the bug**
when i install n-nodes on comfy ui, and i add a work flow the n-nodes don't work. when i relaunch my comfy ui it wont work anymore i have to delete n node in custom node to make comfy ui work again.

**To Reproduce**

**Expected behavior**

**Full log**
This is MANDATORY. By log I mean all the text in the console from the time ComfyUI was started until the time of the reported bug.
>>Bug reports that do not have this log will be closed.<<

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Nuked88** [comment]
Full log
This is MANDATORY. By log I mean all the text in the console from the time ComfyUI was started until the time of the reported bug.
