### ISSUE TITLE
'Logger' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by testFaze** [Nuked88/ComfyUI-N-Nodes#4]
When I run this the GPT Loader is failing with the message:
'Logger' object has no attribute 'fileno'
I believe I have all the dependencies.
Any idea what could cause this?

**Comment by Nuked88** [comment]
Yes, see [THIS](https://github.com/Nuked88/ComfyUI-N-Nodes/issues/2#issuecomment-1712773909)

**Comment by testFaze** [comment]
Thank you - sorry I should have checked closed issues.
It works fine now, thanks for building this.

**Comment by Nuked88** [comment]
it's fine don't worry!
