### ISSUE TITLE
Please add a switch to show/hide the prefix Set_ and Get_

### ISSUE THREAD

**Issue by hiowenluke** [Nuked88/ComfyUI-N-Nodes#45]
SetNode and GetNode make it possible for the input in node to connect wirelessly, making up for anything everywhere.

This is a very clever design, it helps me a lot, thank you so much.

I am now very accustomed to putting GetNode on the left side of the group (indicating input) and SetNode on the right side of the group (indicating output). This clearly represents the I/O structure of the group (yes it looks like a function), as shown in the following figure:

<img width="810" alt="group" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/19872828/f141c36d-e82b-4df6-9d86-1e74230fa43c">

As shown above, I have manually removed the prefixes Get_ and Set_ . In this way, their titles are exactly the same as the node titles of Anything Everywhere, which looks very comfortable.

If the prefixes Get_ and Set_ are not removed, it will look like the variables use different naming rules, which looks very uncomfortable, as shown in the following figure:

<img width="1319" alt="uncomfortable" src="https://github.com/Nuked88/ComfyUI-N-Nodes/assets/19872828/112f6f9d-99d3-486e-a227-98d2b250421b">

Now the trouble I'm having is:

If there is a SetNode that corresponds to multiple GetNodes, when I modify the title of SetNode, the titles of all other corresponding GetNodes will be automatically modified and the Get_ prefix will be added again. It's not pleasant to manually remove these Get_ prefixes again.

Therefore, I would like to be able to have a switch that can turn off the prefixes Set_ and Get_ .

Or do you have a better solution?
Thanks.

**Comment by Nuked88** [comment]
i think you are in the wrong repo 🤣
