### ISSUE TITLE
How do you display text?

### ISSUE THREAD

**Issue by softyoda** [Nuked88/ComfyUI-N-Nodes#55]
Where did you grab this display text node with 🐍icon ?

**Comment by Nuked88** [comment]
Wait. What? Where? XD

**Comment by softyoda** [comment]
It was here : 
![firefox-Nuked88ComfyUI-N-Nodes_A_suite_of_custom_nodes_f-04-03_10-mai-24_6059-49557_1167-907](https://github.com/Nuked88/ComfyUI-N-Nodes/assets/13988751/f6cccf25-7067-4821-9538-079ef21b36e5)


But i found it : it's here : https://github.com/pythongosssss/ComfyUI-Custom-Scripts (but it has a huge ton of unrelated node)

**Comment by Nuked88** [comment]
Yes is that one!
