### ISSUE TITLE
[BUG] Choose file to upload function is missing

### ISSUE THREAD

**Issue by Yennis-C** [Nuked88/ComfyUI-N-Nodes#70]
**Describe the bug**
Choose file to upload function is missing on the loadvideo [n-suite] node
![missing](https://github.com/user-attachments/assets/c61b61b1-9db4-4107-a1cd-220981dde855)

**Expected behavior**
![image-13](https://github.com/user-attachments/assets/9c1a3a7b-b0b4-4118-84cd-c1afe01bd21d)

**Additional context**
I just installed this to tried out yesterday, wonder if this bug is due to the update on 3 days ago?

Thanks.

**Comment by mingieseok** [comment]
Same problem here. I can't drag and drop either. Could you please look into this?

**Comment by guymass** [comment]
Same problem.

**Comment by Nuked88** [comment]
It was a problem related to the last  PR #69 .
Anywayyy i've updated this node with an use_ram option, I hope it comes in handy!
