### ISSUE TITLE
[BUG] Missing 'Choose file to upload button'.

### ISSUE THREAD

**Issue by mingieseok** [Nuked88/ComfyUI-N-Nodes#71]
**Describe the bug**

When I loaded the Loadvideo N-SUITE node to my workflow, there is no upload file button like the description on the github. Drag and drop image wouldn't work either.

**To Reproduce**

Add 'Loadvideo' nodes to the workflow. But there is no upload video button on the node.

**Expected behavior**
I was expecting that there was a upload video button in the Loadvideo node like the description image. But there isn't any button like this. 

![image](https://github.com/user-attachments/assets/b2fa897d-311e-4707-b2b8-7f7b03a619a2)

**Full log**
This is MANDATORY. By log I mean all the text in the console from the time ComfyUI was started until the time of the reported bug:

Not sure what full log means but only thing I did was loading the Loadvideo nodes to my workflow. 

**Screenshots**
<img width="225" alt="Screenshot 2024-07-25 025854" src="https://github.com/user-attachments/assets/40b91cc8-04d1-4980-88a2-c6bc205470d3">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Chrome Version 126.0.6478.128 (Official Build) (64-bit)

**Comment by guymass** [comment]
Hi I have the same issue, there is no upload button and I cannot insert any video into that node.
My other LoadVideo nodes work just fine.

Ubuntu 22.04
Chromium Browser

**Comment by Nuked88** [comment]
See #70
