### ISSUE TITLE
[BUG] Load Video & Save Video not showing up.

### ISSUE THREAD

**Issue by kailashlale** [Nuked88/ComfyUI-N-Nodes#82]
I tried adding Comfy N nodes for fresh ComfyUI Installation.
Tried the `git clone` method and also tried using `Comfyui Manager` to reinstall it.

Also tried deleting Nsuite files from `styles`, `web/extensions`, and `custom_nodes` to re-install it again.

Tried `migrate.bat`, `install_extra.bat`, `remove_extra.bat` in different sequence but no luck.

![image](https://github.com/user-attachments/assets/5b7ac4be-8228-4b98-a3dc-ed15c9eb6617)

**Comment by vollero** [comment]
I think it's a library version issue. I solved it this way:
```
pip uninstall moviepy
pip install moviepy==1.0.3
```
and updating the module

**Comment by kailashlale** [comment]
> I think it's a library version issue. I solved it this way:
> 
> ```
> pip uninstall moviepy
> pip install moviepy==1.0.3
> ```
> 
> and updating the module

Thanks @vollero. This worked for me.
