### ISSUE TITLE
ERROR segment anything

### ISSUE THREAD

**Issue by t8ja** [Nuked88/ComfyUI-N-Nodes#9]
**VIDEO input NODE**

```
Error occurred when executing GroundingDinoSAMSegment (segment anything):

cannot unpack non-iterable NoneType object

  File "/mnt/starT/AI/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/starT/AI/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/starT/AI/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/starT/AI/ComfyUI/custom_nodes/comfyui_segment_anything/node.py", line 305, in main
    (images, masks) = sam_segment(
    ^^^^^^^^^^^^^^^
```

**FRAME input NODE**

```
`Error occurred when executing GroundingDinoSAMSegment (segment anything):

list index out of range
```
**Last line is different**
  ```

    File "/mnt/starT/AI/ComfyUI/execution.py", line 59, in slice_dict
    d_new[k] = v[i if len(v) > i else -1]
               ~^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by t8ja** [comment]
I even tried git cloning everything again and tried running that in both venv's I created. Same result in all cases

**Comment by Nuked88** [comment]
uhm i don't know man maybe you can ask to the author of that node now that is clear that is not some bug of mine since even WAS give the same problem

**Comment by t8ja** [comment]
No, no, your nodes never worked properly. I only got them to output 1 image at a time. Was worked most of the time, until the memory started getting low so sometimes it wouldn't render a few of starting frames and then it would continue till the end, or fail due to lack of memory. Now none of them work, but there are no errors in console, except these... wait, I'll also post the ones Was gives for reference

**Comment by t8ja** [comment]
It's exactly the same like your VIDEO node. 

`Error occurred when executing GroundingDinoSAMSegment (segment anything):

cannot unpack non-iterable NoneType object

  File "/mnt/starT/AI/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/starT/AI/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/starT/AI/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/starT/AI/ComfyUI/custom_nodes/comfyui_segment_anything/node.py", line 305, in main
    (images, masks) = sam_segment(
    ^^^^^^^^^^^^^^^`

**Comment by t8ja** [comment]
WAS works when remove GroundingDINO from the loop. 
Now I'll try yours, tho that should've occurred to me earlier...

**Comment by Nuked88** [comment]
> No, no, your nodes never worked properly (but produced no ERRORS). I only got them to output 1 image at a time (including the preview video consisting of 1 frame).
> 
> WAS worked most of the time, until VRAM started getting low so sometimes it wouldn't render a few starting frames and then it would continue till the end, or fail due to lack of memory. Now none of them work, but there are no errors in console, except these... wait, I'll also post the ones Was gives for reference

without any context of your workflow is pretty impossible for me tell you the reason behind that, could be just your cpu that is slow (since my node is not using gpu except maybe the frameinterpolator) or just the fact that you are passing too much frames at the time without baching them. Just watch the task manager to see how much ram is used (not VRAM), if is too much then is possible that GPU is using your RAM because VRAM is full causing everything to run really slow.
That situation could be caused by batch too big, no batch at all, or even frames too big in size (width X height)
Let me know!

**Comment by t8ja** [comment]
Your nodes also work without DINO in the loop.  The Save NODE even has the preview of the video, tho the LOADER is still blank.

**Comment by Nuked88** [comment]
what do you mean "the loader still blank"?

**Comment by t8ja** [comment]
The preview on the LoadVideo node

**Comment by Nuked88** [comment]
Oh this is probably a problem with the encoding of the original video, try to put the final video outputted by the SaveVideo in the LoadVideo

**Comment by t8ja** [comment]
`** ComfyUI start up time: 2023-10-09 21:18:18.064033

Prestartup times for custom nodes:
   0.2 seconds: /mnt/starT/AI/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 8113 MB, total RAM 15916 MB
xformers version: 0.0.23.dev643
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
### Loading: ComfyUI-Impact-Pack (V4.16.7)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.4)
### Loading: ComfyUI-Manager (V0.34)
### ComfyUI Revision: 1549 [d1a0abd4] | Released on '2023-10-09'
moviepy is already installed.
cv2 is already installed.
git is already installed.
zipfile is already installed.
skbuild is already installed.
Loaded 3.x/4.x HD model.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite: `ffmpeg_bin_path` is set to: /bin/ffmpeg
WAS Node Suite: Finished. Loaded 196 nodes successfully.

`

**Comment by Nuked88** [comment]
no lol i mean the mp4 created by the SaveVideo! Drag it in the load video and see if the preview of the LoadVideo is working for that video

**Comment by t8ja** [comment]
> Oh this is probably a problem with the encoding of the original video, try to put the final video outputted by the SaveVideo in the LoadVideo

You're right

**Comment by Nuked88** [comment]
perfect!

**Comment by t8ja** [comment]
Now how do we trick THE DINO ?

**Comment by t8ja** [comment]
WAS works on a different fork that wasn't updated... perhaps this obfuscation was introduced intentionally ? @ltdrdata s updated fork is also malfunctional

**Comment by t8ja** [comment]
Appears all this could be due to the "threshold" setting on the DINO, 0.5 or above creates the error, but there are still weird things happening, like your nodes appearing without the tickable options to save, or without the button to select the input folder

**Comment by t8ja** [comment]
I spoke too soon. This sheite is upredictable. It worked the first time, now it just doesn't output anything and doesn't error out. Now I'm resetting the UI to check if "the first run" always works... that would at least be orderly

**Comment by t8ja** [comment]
`got prompt
Temporary folder /mnt/starT/AI/ComfyUI/temp/n-suite/frames has been emptied.
The video has 30 frames per second.
Temporary folder /mnt/starT/AI/ComfyUI/output/n-suite/frames_out has been emptied.
The video has been reduced to 7 frames per second.
70 frames have been extracted from the video and saved in /mnt/starT/AI/ComfyUI/output/n-suite/frames_out
MoviePy - Writing audio in /mnt/starT/AI/ComfyUI/temp/audio.mp3
MoviePy - Done.                                                                                                                                               
LR SCALES: [0.08589934592000005, 0.10737418240000006, 0.13421772800000006, 0.1677721600000001, 0.20971520000000007, 0.2621440000000001, 0.3276800000000001, 0.4096000000000001, 0.5120000000000001, 0.6400000000000001, 0.8, 1.0]
<All keys matched successfully>
final text_encoder_type: bert-base-uncased
Temporary folder /mnt/starT/AI/ComfyUI/temp/n-suite/frames has been emptied.
Prompt executed in 85.09 seconds
`
No output 

still upredictable

**Comment by t8ja** [comment]
Interestingly WAS does output (unpredictably, a few frames) at threshold=0.45 (while the error message is on screen) 
`cannot unpack non-iterable NoneType object`

That's exactly what I described was happening before too, but I didn't pay enough attention to what the error said, hence I forgot while messing with other stuff I thought was connected

**Comment by t8ja** [comment]
Around 0.44 seem to be the tipping point. If this is due to CPU load, is there any way to delay execution of each frame. 

The result with your nodes doesn't change even if I reduce the frames to a quarter and increase the batch as far as I can before it.

This MoviePy thing is slow as hell, could u use an ffmpeg library like WAS ? 
Perhaps add an option to strip the audio also

**Comment by t8ja** [comment]
your nodes output nothing if batch=70 while there are 70 frames when video is decomposed, yet it does output when batch=1, threshold 0.3 in both cases, yet at 0.35 it errors

**Comment by t8ja** [comment]
Input image size might be the actual culprit, width of 512 doesn't error at least till 0.37... but I have no idea why increasing the batch doesn't affect anything

**Comment by Nuked88** [comment]
man i think you haven't really grasped the concept of "batch" xD
Having 70 frames and set a batch size of 70 is the equivalent of not using batches.

Using batches is a way for you to split the work of your GPU divinding some big work in "subworks"

If you have 70 frames i will start, for example, with a batch size of 10  so that you can split the  work in  7 (70/10)  "subworks"
